In [3]:
import numpy as np
import pandas as pd

In [9]:
s1 = pd.Series([1, 2, 3, 4, 5])
s2 = pd.Series([6, 7, 8, 9, 10])
df = pd.DataFrame({"first": s1, "second": s2})
print(df)
print(type(df))
print(type(df["first"]))

df = pd.DataFrame(
    {
        # "id": [1, 2, 3, 4, 5],
        "name": ["tom", "jack", "alice", "bob", "allen"],
        "age": [15, 17, 20, 26, 30],
        "score": [60.5, 80, 30.6, 70, 83.5],
    },
    index=[1, 2, 3, 4, 5],
    columns=["name", "score", "age"],
)
df

   first  second
0      1       6
1      2       7
2      3       8
3      4       9
4      5      10
<class 'pandas.DataFrame'>
<class 'pandas.Series'>

    name  score  age
1    tom   60.5   15
2   jack   80.0   17
3  alice   30.6   20
4    bob   70.0   26
5  allen   83.5   30

In [12]:
print(df.index)
print(df.columns)
print(df.values)

Index([1, 2, 3, 4, 5], dtype='int64')
Index(['name', 'score', 'age'], dtype='str')
[['tom' 60.5 15]
 ['jack' 80.0 17]
 ['alice' 30.6 20]
 ['bob' 70.0 26]
 ['allen' 83.5 30]]

In [18]:
print(df.ndim)
print(df.shape)
print(df.size)
print(df.dtypes)

2
(5, 3)
15
name         str
score    float64
age        int64
dtype: object

In [21]:
print(df.T)
df

          1     2      3     4      5
name    tom  jack  alice   bob  allen
score  60.5  80.0   30.6  70.0   83.5
age      15    17     20    26     30

    name  score  age
1    tom   60.5   15
2   jack   80.0   17
3  alice   30.6   20
4    bob   70.0   26
5  allen   83.5   30

In [28]:
print(df.loc[4])
print(df.iloc[3])

print(df.loc[:, "name"])
print(df.iloc[:, 0])

name      bob
score    70.0
age        26
Name: 4, dtype: object
name      bob
score    70.0
age        26
Name: 4, dtype: object
1      tom
2     jack
3    alice
4      bob
5    allen
Name: name, dtype: str
1      tom
2     jack
3    alice
4      bob
5    allen
Name: name, dtype: str

In [31]:
print(df.at[3, "score"])
print(df.iat[2, 1])

30.6
30.6

In [36]:
print(df["name"])
print(type(df["name"]))
print(df.name)
print(type(df.name))
print(df[["name"]])
print(type(df[["name"]]))

1      tom
2     jack
3    alice
4      bob
5    allen
Name: name, dtype: str
<class 'pandas.Series'>
1      tom
2     jack
3    alice
4      bob
5    allen
Name: name, dtype: str
<class 'pandas.Series'>
    name
1    tom
2   jack
3  alice
4    bob
5  allen
<class 'pandas.DataFrame'>

In [39]:
df[["name", "score"]]

    name  score
1    tom   60.5
2   jack   80.0
3  alice   30.6
4    bob   70.0
5  allen   83.5

In [41]:
print(df.head(2))
print(df.tail(3))

   name  score  age
1   tom   60.5   15
2  jack   80.0   17
    name  score  age
3  alice   30.6   20
4    bob   70.0   26
5  allen   83.5   30

In [ ]:
df[df.score > 70]
df[(df.score > 70) & (df.age < 20)]

   name  score  age
2  jack   80.0   17