In [1]:
import numpy as np
import pandas as pd

In [2]:
s1 = pd.Series([1, 2, 3, 4, 5])
s2 = pd.Series([6, 7, 8, 9, 10])
df = pd.DataFrame({"first": s1, "second": s2})
print(df)
print(type(df))
print(type(df["first"]))

df = pd.DataFrame(
    {
        # "id": [1, 2, 3, 4, 5],
        "name": ["tom", "jack", "alice", "bob", "allen"],
        "age": [15, 17, 20, 26, 30],
        "score": [60.5, 80, 30.6, 70, 83.5],
    },
    index=[1, 2, 3, 4, 5],
    columns=["name", "score", "age"],
)
df

   first  second
0      1       6
1      2       7
2      3       8
3      4       9
4      5      10
<class 'pandas.DataFrame'>
<class 'pandas.Series'>

    name  score  age
1    tom   60.5   15
2   jack   80.0   17
3  alice   30.6   20
4    bob   70.0   26
5  allen   83.5   30

In [3]:
print(df.index)
print(df.columns)
print(df.values)

Index([1, 2, 3, 4, 5], dtype='int64')
Index(['name', 'score', 'age'], dtype='str')
[['tom' 60.5 15]
 ['jack' 80.0 17]
 ['alice' 30.6 20]
 ['bob' 70.0 26]
 ['allen' 83.5 30]]

In [4]:
print(df.ndim)
print(df.shape)
print(df.size)
print(df.dtypes)

2
(5, 3)
15
name         str
score    float64
age        int64
dtype: object

In [5]:
print(df.T)
df

          1     2      3     4      5
name    tom  jack  alice   bob  allen
score  60.5  80.0   30.6  70.0   83.5
age      15    17     20    26     30

    name  score  age
1    tom   60.5   15
2   jack   80.0   17
3  alice   30.6   20
4    bob   70.0   26
5  allen   83.5   30

In [6]:
print(df.loc[4])
print(df.iloc[3])

print(df.loc[:, "name"])
print(df.iloc[:, 0])

name      bob
score    70.0
age        26
Name: 4, dtype: object
name      bob
score    70.0
age        26
Name: 4, dtype: object
1      tom
2     jack
3    alice
4      bob
5    allen
Name: name, dtype: str
1      tom
2     jack
3    alice
4      bob
5    allen
Name: name, dtype: str

In [7]:
print(df.at[3, "score"])
print(df.iat[2, 1])

30.6
30.6

In [8]:
print(df["name"])
print(type(df["name"]))
print(df.name)
print(type(df.name))
print(df[["name"]])
print(type(df[["name"]]))

1      tom
2     jack
3    alice
4      bob
5    allen
Name: name, dtype: str
<class 'pandas.Series'>
1      tom
2     jack
3    alice
4      bob
5    allen
Name: name, dtype: str
<class 'pandas.Series'>
    name
1    tom
2   jack
3  alice
4    bob
5  allen
<class 'pandas.DataFrame'>

In [9]:
df[["name", "score"]]

    name  score
1    tom   60.5
2   jack   80.0
3  alice   30.6
4    bob   70.0
5  allen   83.5

In [10]:
print(df.head(2))
print(df.tail(3))

   name  score  age
1   tom   60.5   15
2  jack   80.0   17
    name  score  age
3  alice   30.6   20
4    bob   70.0   26
5  allen   83.5   30

In [11]:
df[df.score > 70]
df[(df.score > 70) & (df.age < 20)]

   name  score  age
2  jack   80.0   17

In [12]:
df.sample(3)

    name  score  age
1    tom   60.5   15
3  alice   30.6   20
5  allen   83.5   30

In [13]:
df

    name  score  age
1    tom   60.5   15
2   jack   80.0   17
3  alice   30.6   20
4    bob   70.0   26
5  allen   83.5   30

In [14]:
print(df.head())
print(df.tail())

    name  score  age
1    tom   60.5   15
2   jack   80.0   17
3  alice   30.6   20
4    bob   70.0   26
5  allen   83.5   30
    name  score  age
1    tom   60.5   15
2   jack   80.0   17
3  alice   30.6   20
4    bob   70.0   26
5  allen   83.5   30

In [15]:
print(df.isin(["jack", 20]))

    name  score    age
1  False  False  False
2   True  False  False
3  False  False   True
4  False  False  False
5  False  False  False

In [16]:
print(df.isna())

    name  score    age
1  False  False  False
2  False  False  False
3  False  False  False
4  False  False  False
5  False  False  False

In [17]:
print(df.score.sum())
print(df["score"].max())
print(df.age.min())
print(df.score.mean())
print(df.score.median())
print(df.score.mode())
print(df.score.std())
print(df.score.var())
print(df.score.quantile(0.25))

324.6
83.5
15
64.92
70.0
0    30.6
1    60.5
2    70.0
3    80.0
4    83.5
Name: score, dtype: float64
21.188605428390044
448.957
60.5

In [18]:
print(df.describe())
print(df.count())

           score        age
count   5.000000   5.000000
mean   64.920000  21.600000
std    21.188605   6.268971
min    30.600000  15.000000
25%    60.500000  17.000000
50%    70.000000  20.000000
75%    80.000000  26.000000
max    83.500000  30.000000
name     5
score    5
age      5
dtype: int64

In [22]:
print(df.value_counts())
print(df.drop_duplicates())
print(df.duplicated(subset=["age"]))

name   score  age
tom    60.5   15     1
jack   80.0   17     1
alice  30.6   20     1
bob    70.0   26     1
allen  83.5   30     1
Name: count, dtype: int64
    name  score  age
1    tom   60.5   15
2   jack   80.0   17
3  alice   30.6   20
4    bob   70.0   26
5  allen   83.5   30
1    False
2    False
3    False
4    False
5    False
dtype: bool

In [25]:
df.sample(2)

    name  score  age
3  alice   30.6   20
4    bob   70.0   26

In [28]:
print(df.replace(15, 30))

    name  score  age
1    tom   60.5   30
2   jack   80.0   17
3  alice   30.6   20
4    bob   70.0   26
5  allen   83.5   30

In [31]:
print(df.cumsum())
print(df.cummax())
print(df.cummin())

                   name  score  age
1                   tom   60.5   15
2               tomjack  140.5   32
3          tomjackalice  171.1   52
4       tomjackalicebob  241.1   78
5  tomjackaliceboballen  324.6  108
  name  score  age
1  tom   60.5   15
2  tom   80.0   17
3  tom   80.0   20
4  tom   80.0   26
5  tom   83.5   30
    name  score  age
1    tom   60.5   15
2   jack   60.5   15
3  alice   30.6   15
4  alice   30.6   15
5  alice   30.6   15

In [38]:
print(df.sort_index(ascending=False))
print(df.sort_values(by=["score", "age"], ascending=[True, False]))

    name  score  age
5  allen   83.5   30
4    bob   70.0   26
3  alice   30.6   20
2   jack   80.0   17
1    tom   60.5   15
    name  score  age
3  alice   30.6   20
1    tom   60.5   15
4    bob   70.0   26
2   jack   80.0   17
5  allen   83.5   30

In [40]:
print(df.nlargest(2, columns=["score", "age"]))
print(df.nsmallest(2, columns=["score", "age"]))

    name  score  age
5  allen   83.5   30
2   jack   80.0   17
    name  score  age
3  alice   30.6   20
1    tom   60.5   15