In [47]:
import pandas as pd

In [48]:
df = pd.read_csv("data/employees.csv")
print(type(df))
print(df.tail())
print(df.salary.mean())

<class 'pandas.DataFrame'>
     employee_id first_name last_name     email  phone_number      job_id  \
102          202        Pat       Fay      PFAY  603.123.6666      MK_REP
103          203      Susan    Mavris   SMAVRIS  515.123.7777      HR_REP
104          204    Hermann      Baer     HBAER  515.123.8888      PR_REP
105          205    Shelley   Higgins  SHIGGINS  515.123.8080      AC_MGR
106          206    William     Gietz    WGIETZ  515.123.8181  AC_ACCOUNT

      salary  commission_pct  manager_id  department_id
102   6000.0             NaN       201.0           20.0
103   6500.0             NaN       101.0           40.0
104  10000.0             NaN       101.0           70.0
105  12000.0             NaN       101.0          110.0
106   8300.0             NaN       205.0          110.0
6461.682242990654

In [49]:
df = df.tail()
df.to_csv("data/new.csv")

In [50]:
df = pd.read_json("data/data1.json")

import json

with open("data/test.json", encoding="utf-8") as f:
    data = json.load(f)

print(data)
print(type(data))

df = pd.DataFrame(data["users"])
print(type(df))
df

{'users': [{'id': 1, 'name': '张三', 'age': 28, 'email': 'zhangsan@example.com', 'is_active': True, 'join_date': '2022-03-15'}, {'id': 2, 'name': '李四', 'age': 35, 'email': 'lisi@example.com', 'is_active': False, 'join_date': '2021-11-02'}, {'id': 3, 'name': '王五', 'age': 24, 'email': 'wangwu@example.com', 'is_active': True, 'join_date': '2023-01-20'}]}
<class 'dict'>
<class 'pandas.DataFrame'>

   id name  age                 email  is_active   join_date
0   1   张三   28  zhangsan@example.com       True  2022-03-15
1   2   李四   35      lisi@example.com      False  2021-11-02
2   3   王五   24    wangwu@example.com       True  2023-01-20

In [51]:
import numpy as np
import pandas as pd

s = pd.Series([1, 2, np.nan, None, pd.NA])
df = pd.DataFrame([[1, pd.NA, 2], [2, 3, 5], [None, 4, 6]])

print(s)
print(s.isna())
print(s.isnull())

print(df.isna())
print(df.isnull())
print(df.isna().sum(axis=1))

0       1
1       2
2     NaN
3    None
4    <NA>
dtype: object
0    False
1    False
2     True
3     True
4     True
dtype: bool
0    False
1    False
2     True
3     True
4     True
dtype: bool
       0      1      2
0  False   True  False
1  False  False  False
2   True  False  False
       0      1      2
0  False   True  False
1  False  False  False
2   True  False  False
0    1
1    0
2    1
dtype: int64

In [52]:
print(s.dropna())
print(df.dropna(how="all"))
print(df.dropna(thresh=2))
print(df.dropna(axis=1))
print(df.dropna(subset=[1]))

0    1
1    2
dtype: object
     0     1  2
0  1.0  <NA>  2
1  2.0     3  5
2  NaN     4  6
     0     1  2
0  1.0  <NA>  2
1  2.0     3  5
2  NaN     4  6
   2
0  2
1  5
2  6
     0  1  2
1  2.0  3  5
2  NaN  4  6

In [53]:
df = pd.read_csv("data/weather_withna.csv")
print(df.head())
print(df.tail())
print(df.isna().sum(axis=0))
print(df.fillna({"temp_max": 20, "wind": 2.5}).tail())
print(df.fillna(df[["temp_max", "wind"]].mean()).tail())
print(df.ffill().tail())
print(df.bfill().tail())

         date  precipitation  temp_max  temp_min  wind  weather
0  2012-01-01            0.0      12.8       5.0   4.7  drizzle
1  2012-01-02           10.9      10.6       2.8   4.5     rain
2  2012-01-03            0.8      11.7       7.2   2.3     rain
3  2012-01-04           20.3      12.2       5.6   4.7     rain
4  2012-01-05            1.3       8.9       2.8   6.1     rain
            date  precipitation  temp_max  temp_min  wind weather
1456  2015-12-27            NaN       NaN       NaN   NaN     NaN
1457  2015-12-28            NaN       NaN       NaN   NaN     NaN
1458  2015-12-29            NaN       NaN       NaN   NaN     NaN
1459  2015-12-30            NaN       NaN       NaN   NaN     NaN
1460  2015-12-31           20.6      12.2       5.0   3.8    rain
date               0
precipitation    303
temp_max         303
temp_min         303
wind             303
weather          303
dtype: int64
            date  precipitation  temp_max  temp_min  wind weather
1456  2015-12-27            NaN      20.0       NaN   2.5     NaN
1457  2015-12-28            NaN      20.0       NaN   2.5     NaN
1458  2015-12-29            NaN      20.0       NaN   2.5     NaN
1459  2015-12-30            NaN      20.0       NaN   2.5     NaN
1460  2015-12-31           20.6      12.2       5.0   3.8    rain
            date  precipitation   temp_max  temp_min      wind weather
1456  2015-12-27            NaN  15.851468       NaN  3.242055     NaN
1457  2015-12-28            NaN  15.851468       NaN  3.242055     NaN
1458  2015-12-29            NaN  15.851468       NaN  3.242055     NaN
1459  2015-12-30            NaN  15.851468       NaN  3.242055     NaN
1460  2015-12-31           20.6  12.200000       5.0  3.800000    rain
            date  precipitation  temp_max  temp_min  wind weather
1456  2015-12-27            0.0      11.1       4.4   4.8     sun
1457  2015-12-28            0.0      11.1       4.4   4.8     sun
1458  2015-12-29            0.0      11.1       4.4   4.8     sun
1459  2015-12-30            0.0      11.1       4.4   4.8     sun
1460  2015-12-31           20.6      12.2       5.0   3.8    rain
            date  precipitation  temp_max  temp_min  wind weather
1456  2015-12-27           20.6      12.2       5.0   3.8    rain
1457  2015-12-28           20.6      12.2       5.0   3.8    rain
1458  2015-12-29           20.6      12.2       5.0   3.8    rain
1459  2015-12-30           20.6      12.2       5.0   3.8    rain
1460  2015-12-31           20.6      12.2       5.0   3.8    rain

In [54]:
data = {
    "name": ["alice", "alice", "bob", "alice", "jack", "bob"],
    "age": [26, 25, 30, 25, 35, 30],
    "city": ["NY", "NY", "LA", "NY", "SF", "LA"],
}

df = pd.DataFrame(data)

In [55]:
print(df.duplicated())
print(df.drop_duplicates(subset=["name"], keep="last"))

0    False
1    False
2    False
3     True
4    False
5     True
dtype: bool
    name  age city
3  alice   25   NY
4   jack   35   SF
5    bob   30   LA

In [56]:
df = pd.read_csv("data/sleep.csv")

In [57]:
df

,person_id,gender,age,occupation,sleep_duration,sleep_quality,physical_activity_level,stress_level,bmi_category,blood_pressure,heart_rate,daily_steps,sleep_disorder
0,1,Male,29,Manual Labor,7.4,7.0,41,7,Obese,124/70,91,8539,NaN
1,2,Female,43,Retired,4.2,4.9,41,5,Obese,131/86,81,18754,NaN
2,3,Male,44,Retired,6.1,6.0,107,4,Underweight,122/70,81,2857,NaN
3,4,Male,29,Office Worker,8.3,10.0,20,10,Obese,124/72,55,6886,NaN
4,5,Male,67,Retired,9.1,9.5,19,4,Overweight,133/78,97,14945,Insomnia
...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,396,Female,36,Student,4.5,7.9,73,7,Normal,118/66,64,14497,Sleep Apnea
396,397,Female,45,Manual Labor,6.0,6.1,72,8,Obese,132/80,65,12848,Insomnia
397,398,Female,30,Student,5.3,6.5,58,10,Obese,125/76,66,15255,Insomnia
398,399,Female,41,Retired,11.0,9.1,73,9,Obese,130/75,75,6567,Sleep Apnea
399,400,Male,37,Retired,5.8,7.0,41,6,Normal,118/70,51,18079,NaN

In [58]:
print(df.dtypes)
df["age"] = df["age"].astype("int16")
print(df.dtypes)

person_id                    int64
gender                         str
age                          int64
occupation                     str
sleep_duration             float64
sleep_quality              float64
physical_activity_level      int64
stress_level                 int64
bmi_category                   str
blood_pressure                 str
heart_rate                   int64
daily_steps                  int64
sleep_disorder                 str
dtype: object
person_id                    int64
gender                         str
age                          int16
occupation                     str
sleep_duration             float64
sleep_quality              float64
physical_activity_level      int64
stress_level                 int64
bmi_category                   str
blood_pressure                 str
heart_rate                   int64
daily_steps                  int64
sleep_disorder                 str
dtype: object

In [59]:
df["gender"] = df["gender"].astype("category")
print(df.dtypes)
print(df.gender)

person_id                     int64
gender                     category
age                           int16
occupation                      str
sleep_duration              float64
sleep_quality               float64
physical_activity_level       int64
stress_level                  int64
bmi_category                    str
blood_pressure                  str
heart_rate                    int64
daily_steps                   int64
sleep_disorder                  str
dtype: object
0        Male
1      Female
2        Male
3        Male
4        Male
        ...
395    Female
396    Female
397    Female
398    Female
399      Male
Name: gender, Length: 400, dtype: category
Categories (2, str): ['Female', 'Male']

In [60]:
df["is_male"] = df["gender"].map({"Male": True, "Female": False})
print(df["is_male"].tail())

395    False
396    False
397    False
398    False
399     True
Name: is_male, dtype: category
Categories (2, bool): [False, True]

In [61]:
data = {
    "id": [1, 2],
    "name": ["alice", "bob"],
    "math": [90, 85],
    "english": [88, 92],
    "science": [95, 89],
}

df = pd.DataFrame(data)

In [62]:
df

   id   name  math  english  science
0   1  alice    90       88       95
1   2    bob    85       92       89

In [63]:
print(df.T)

df2 = pd.melt(df, id_vars=["id", "name"], var_name="subjects", value_name="score")
print(df2.sort_values("name"))

print(pd.pivot(df2, index=["id", "name"], columns="subjects", values="score"))

             0    1
id           1    2
name     alice  bob
math        90   85
english     88   92
science     95   89
   id   name subjects  score
0   1  alice     math     90
2   1  alice  english     88
4   1  alice  science     95
1   2    bob     math     85
3   2    bob  english     92
5   2    bob  science     89
subjects  english  math  science
id name
1  alice       88    90       95
2  bob         92    85       89

In [64]:
data = {
    "id": [1, 2],
    "name": ["alice smith", "bob smith"],
    "math": [90, 85],
    "english": [88, 92],
    "science": [95, 89],
}

df = pd.DataFrame(data)

In [65]:
df[["first", "last"]] = df["name"].str.split(" ", expand=True)
print(df)

   id         name  math  english  science  first   last
0   1  alice smith    90       88       95  alice  smith
1   2    bob smith    85       92       89    bob  smith

In [66]:
df = pd.read_csv("data/sleep.csv")
df = df[["person_id", "blood_pressure"]]
df[["high", "low"]] = df["blood_pressure"].str.split("/", expand=True)
print(df)
print(df.info())
df["high"] = df["high"].astype("int64")
df["low"] = df["low"].astype("int64")
print(df.info())
print(df.high.mean())

     person_id blood_pressure high low
0            1         124/70  124  70
1            2         131/86  131  86
2            3         122/70  122  70
3            4         124/72  124  72
4            5         133/78  133  78
..         ...            ...  ...  ..
395        396         118/66  118  66
396        397         132/80  132  80
397        398         125/76  125  76
398        399         130/75  130  75
399        400         118/70  118  70

[400 rows x 4 columns]
<class 'pandas.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   person_id       400 non-null    int64
 1   blood_pressure  400 non-null    str
 2   high            400 non-null    str
 3   low             400 non-null    str
dtypes: int64(1), str(3)
memory usage: 16.9 KB
None
<class 'pandas.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   person_id       400 non-null    int64
 1   blood_pressure  400 non-null    str
 2   high            400 non-null    int64
 3   low             400 non-null    int64
dtypes: int64(3), str(1)
memory usage: 15.0 KB
None
122.19

In [67]:
df = pd.read_csv("data/employees.csv")

In [68]:
df1 = df.head(10)[["employee_id", "salary"]]
df1

   employee_id   salary
0          100  24000.0
1          101  17000.0
2          102  17000.0
3          103   9000.0
4          104   6000.0
5          105   4800.0
6          106   4800.0
7          107   4200.0
8          108  12000.0
9          109   9000.0

In [69]:
print(pd.cut(df1["salary"], bins=2))
print(pd.cut(df1["salary"], bins=2).value_counts())
print(pd.cut(df1["salary"], bins=[0, 10000, 20000, 30000]))
print(pd.cut(df1["salary"], bins=[0, 10000, 20000, 30000]).value_counts())
df1["income range"] = pd.cut(
    df1["salary"], bins=[0, 10000, 20000, 30000], labels=["low", "mid", "high"]
)
print(df1)

0    (14100.0, 24000.0]
1    (14100.0, 24000.0]
2    (14100.0, 24000.0]
3     (4180.2, 14100.0]
4     (4180.2, 14100.0]
5     (4180.2, 14100.0]
6     (4180.2, 14100.0]
7     (4180.2, 14100.0]
8     (4180.2, 14100.0]
9     (4180.2, 14100.0]
Name: salary, dtype: category
Categories (2, interval[float64, right]): [(4180.2, 14100.0] < (14100.0, 24000.0]]
salary
(4180.2, 14100.0]     7
(14100.0, 24000.0]    3
Name: count, dtype: int64
0    (20000, 30000]
1    (10000, 20000]
2    (10000, 20000]
3        (0, 10000]
4        (0, 10000]
5        (0, 10000]
6        (0, 10000]
7        (0, 10000]
8    (10000, 20000]
9        (0, 10000]
Name: salary, dtype: category
Categories (3, interval[int64, right]): [(0, 10000] < (10000, 20000] < (20000, 30000]]
salary
(0, 10000]        6
(10000, 20000]    3
(20000, 30000]    1
Name: count, dtype: int64
   employee_id   salary income range
0          100  24000.0         high
1          101  17000.0          mid
2          102  17000.0          mid
3          103   9000.0          low
4          104   6000.0          low
5          105   4800.0          low
6          106   4800.0          low
7          107   4200.0          low
8          108  12000.0          mid
9          109   9000.0          low

In [70]:
print(pd.qcut(df1["salary"], 3).value_counts())

salary
(4199.999, 6000.0]    4
(6000.0, 12000.0]     3
(12000.0, 24000.0]    3
Name: count, dtype: int64

In [71]:
df = pd.read_csv("data/sleep.csv")
# df1 = df.head(10)[["person_id", "sleep_quality"]]
# df1

In [72]:
df["sleep quality"] = pd.cut(df["sleep_quality"], bins=3, labels=["bad", "mid", "good"])
print(df["sleep quality"].value_counts())

df["gender"] = df["gender"].astype("category")
print(df["gender"].value_counts())

print(df["sleep quality"].dtype)
print(df["gender"].dtype)

sleep quality
mid     206
good    129
bad      65
Name: count, dtype: int64
gender
Female    201
Male      199
Name: count, dtype: int64
category
category

In [73]:
df = pd.DataFrame({
    "name": ["jack", "alice", "tom", "bob"],
    "age": [20, 30, 40, 50],
    "gender": ["male", "female", "male", "male"],
})
df

df.set_index("name", inplace=True)
df.reset_index(inplace=True)
df.rename(columns={"age": "ages"}, index={0: 4})

    name  ages  gender
4   jack    20    male
1  alice    30  female
2    tom    40    male
3    bob    50    male

In [74]:
df.index = [1, 2, 3, 4]
df.columns = ["names", "age", "genders"]
df

   names  age genders
1   jack   20    male
2  alice   30  female
3    tom   40    male
4    bob   50    male

In [75]:
# time data handling
d = pd.Timestamp("2015-05-22 10:22")
print(d)
print(type(d))
print("year: ", d.year)
print("season: ", d.quarter)
print(d.is_month_end)
print(d.day_name())
print(d.to_period("D"))
print(d.to_period("Q"))
print(d.to_period("W"))

2015-05-22 10:22:00
<class 'pandas.Timestamp'>
year:  2015
season:  2
False
Friday
2015-05-22
2015Q2
2015-05-18/2015-05-24

In [76]:
a = pd.to_datetime("2015-05-22 10:22")
print(a)
print(type(a))

df = pd.DataFrame({
    "sales": [100, 200, 300],
    "date": ["20250601", "20250602", "20250603"],
})
df["datetime"] = pd.to_datetime(df["date"])
print(df.info())
df["week"] = df["datetime"].dt.day_name()
print(df)

2015-05-22 10:22:00
<class 'pandas.Timestamp'>
<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   sales     3 non-null      int64
 1   date      3 non-null      str
 2   datetime  3 non-null      datetime64[us]
dtypes: datetime64[us](1), int64(1), str(1)
memory usage: 228.0 bytes
None
   sales      date   datetime     week
0    100  20250601 2025-06-01   Sunday
1    200  20250602 2025-06-02   Monday
2    300  20250603 2025-06-03  Tuesday

In [77]:
# df = pd.read_csv("data/weather.csv")
# df["datetime"] = pd.to_datetime(df["date"])
# print(df.info())

df = pd.read_csv("data/weather.csv", parse_dates=["date"])
df.info()

df.set_index("date", inplace=True)  # datetime data as index
print(df.loc["2013-01":"2013-02"])

<class 'pandas.DataFrame'>
RangeIndex: 1461 entries, 0 to 1460
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           1461 non-null   datetime64[us]
 1   precipitation  1461 non-null   float64
 2   temp_max       1461 non-null   float64
 3   temp_min       1461 non-null   float64
 4   wind           1461 non-null   float64
 5   weather        1461 non-null   str
dtypes: datetime64[us](1), float64(4), str(1)
memory usage: 73.8 KB
            precipitation  temp_max  temp_min  wind  weather
date
2013-01-01            0.0       5.0      -2.8   2.7      sun
2013-01-02            0.0       6.1      -1.1   3.2      sun
2013-01-03            4.1       6.7      -1.7   3.0     rain
2013-01-04            2.5      10.0       2.2   2.8     rain
2013-01-05            3.0       6.7       4.4   3.1     rain
2013-01-06            2.0       7.2       2.8   3.0     rain
2013-01-07            2.3      10.0       4.4   7.3     rain
2013-01-08           16.3      11.7       5.6   6.3     rain
2013-01-09           38.4      10.0       1.7   5.1     rain
2013-01-10            0.3       3.3      -0.6   2.1     snow
2013-01-11            0.0       2.8      -2.8   1.9  drizzle
2013-01-12            0.0       2.8      -3.9   2.0      sun
2013-01-13            0.0       2.2      -4.4   1.5      sun
2013-01-14            0.0       3.3      -2.2   1.3      sun
2013-01-15            0.0       6.7      -0.6   2.3      sun
2013-01-16            0.0       6.1      -3.9   1.8  drizzle
2013-01-17            0.0       3.9      -2.8   1.0  drizzle
2013-01-18            0.0       3.3      -1.1   1.3  drizzle
2013-01-19            0.0       1.1      -0.6   1.9  drizzle
2013-01-20            0.0       3.3      -0.6   2.1  drizzle
2013-01-21            0.0       2.2      -1.7   1.1  drizzle
2013-01-22            0.0       3.3      -1.7   0.6  drizzle
2013-01-23            5.1       7.2       2.2   3.1     rain
2013-01-24            5.8       7.2       1.1   2.6     rain
2013-01-25            3.0      10.6       2.8   2.1     rain
2013-01-26            2.3       8.3       3.9   4.5     rain
2013-01-27            1.8       5.6       3.9   4.5     rain
2013-01-28            7.9       6.1       3.3   3.2     rain
2013-01-29            4.3       8.3       5.0   3.9     rain
2013-01-30            3.6       8.9       6.7   3.9     rain
2013-01-31            3.0       9.4       7.2   4.0     rain
2013-02-01            0.3      11.7       5.0   2.9     rain
2013-02-02            0.0       6.1       2.8   2.0  drizzle
2013-02-03            2.3       8.9       2.8   2.9     rain
2013-02-04            0.0      10.6       6.7   2.6     rain
2013-02-05            3.3      10.0       6.7   5.1     rain
2013-02-06            1.0      10.6       6.1   4.5     rain
2013-02-07            1.3       9.4       3.3   4.1     rain
2013-02-08            0.0       7.8       2.2   1.3      sun
2013-02-09            0.3       8.3       4.4   1.3     rain
2013-02-10            0.0       8.9       1.7   2.0  drizzle
2013-02-11            0.3       8.3       4.4   1.4     rain
2013-02-12            1.0      11.1       7.2   5.6     rain
2013-02-13            2.3       9.4       7.2   4.1     rain
2013-02-14            1.0       9.4       5.6   2.2     rain
2013-02-15            0.0      13.3       5.0   2.4  drizzle
2013-02-16            0.0      11.1       3.9   5.6     rain
2013-02-17            0.0       9.4       4.4   3.4     rain
2013-02-18            0.0       7.8       3.9   1.9     rain
2013-02-19            0.0      10.6       1.7   3.4      sun
2013-02-20            1.5       7.8       1.1   2.1     rain
2013-02-21            0.5       6.7       3.9   6.2     rain
2013-02-22            9.4       7.8       3.9   8.1     rain
2013-02-23            0.3      10.0       3.9   4.6     rain
2013-02-24            0.0       8.9       5.0   5.5     rain
2013-02-25            2.3      10.6       3.3   7.1     rain
2013-02-26            0.5       8.9       3.9   3.8     rain
2013-02-27            4.6      10.0       4.4   1.8     rain
2013-02-28            8.1      11.7       6.7   3.8     rain

In [78]:
d1 = pd.Timestamp("2013-01-15")
d2 = pd.Timestamp("2023-02-23")
d3 = d2 - d1
print(type(d3))
print(d3)

<class 'pandas.Timedelta'>
3691 days 00:00:00

In [79]:
df = pd.read_csv("data/weather.csv", parse_dates=["date"])
df.info()

df["delta"] = df["date"] - df["date"][0]
df.set_index("delta", inplace=True)
print(df)

print(df.loc["10 days":"20 days"])

<class 'pandas.DataFrame'>
RangeIndex: 1461 entries, 0 to 1460
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           1461 non-null   datetime64[us]
 1   precipitation  1461 non-null   float64
 2   temp_max       1461 non-null   float64
 3   temp_min       1461 non-null   float64
 4   wind           1461 non-null   float64
 5   weather        1461 non-null   str
dtypes: datetime64[us](1), float64(4), str(1)
memory usage: 73.8 KB
                date  precipitation  temp_max  temp_min  wind  weather
delta
0 days    2012-01-01            0.0      12.8       5.0   4.7  drizzle
1 days    2012-01-02           10.9      10.6       2.8   4.5     rain
2 days    2012-01-03            0.8      11.7       7.2   2.3     rain
3 days    2012-01-04           20.3      12.2       5.6   4.7     rain
4 days    2012-01-05            1.3       8.9       2.8   6.1     rain
...              ...            ...       ...       ...   ...      ...
1456 days 2015-12-27            8.6       4.4       1.7   2.9     rain
1457 days 2015-12-28            1.5       5.0       1.7   1.3     rain
1458 days 2015-12-29            0.0       7.2       0.6   2.6      fog
1459 days 2015-12-30            0.0       5.6      -1.0   3.4      sun
1460 days 2015-12-31            0.0       5.6      -2.1   3.5      sun

[1461 rows x 6 columns]
              date  precipitation  temp_max  temp_min  wind weather
delta
10 days 2012-01-11            0.0       6.1      -1.1   5.1     sun
11 days 2012-01-12            0.0       6.1      -1.7   1.9     sun
12 days 2012-01-13            0.0       5.0      -2.8   1.3     sun
13 days 2012-01-14            4.1       4.4       0.6   5.3    snow
14 days 2012-01-15            5.3       1.1      -3.3   3.2    snow
15 days 2012-01-16            2.5       1.7      -2.8   5.0    snow
16 days 2012-01-17            8.1       3.3       0.0   5.6    snow
17 days 2012-01-18           19.8       0.0      -2.8   5.0    snow
18 days 2012-01-19           15.2      -1.1      -2.8   1.6    snow
19 days 2012-01-20           13.5       7.2      -1.1   2.3    snow
20 days 2012-01-21            3.0       8.3       3.3   8.2    rain

In [80]:
days = pd.date_range("2025-07-03", "2026-02-09", freq="W")
print(days)
days = pd.date_range("2025-07-03", periods=10, freq="W")
print(days)
days = pd.date_range("2025-07-03", periods=10, freq="YS")
print(days)
days = pd.date_range("2025-07-03", periods=10, freq="YE")
print(days)

DatetimeIndex(['2025-07-06', '2025-07-13', '2025-07-20', '2025-07-27',
               '2025-08-03', '2025-08-10', '2025-08-17', '2025-08-24',
               '2025-08-31', '2025-09-07', '2025-09-14', '2025-09-21',
               '2025-09-28', '2025-10-05', '2025-10-12', '2025-10-19',
               '2025-10-26', '2025-11-02', '2025-11-09', '2025-11-16',
               '2025-11-23', '2025-11-30', '2025-12-07', '2025-12-14',
               '2025-12-21', '2025-12-28', '2026-01-04', '2026-01-11',
               '2026-01-18', '2026-01-25', '2026-02-01', '2026-02-08'],
              dtype='datetime64[us]', freq='W-SUN')
DatetimeIndex(['2025-07-06', '2025-07-13', '2025-07-20', '2025-07-27',
               '2025-08-03', '2025-08-10', '2025-08-17', '2025-08-24',
               '2025-08-31', '2025-09-07'],
              dtype='datetime64[us]', freq='W-SUN')
DatetimeIndex(['2026-01-01', '2027-01-01', '2028-01-01', '2029-01-01',
               '2030-01-01', '2031-01-01', '2032-01-01', '2033-01-01',
               '2034-01-01', '2035-01-01'],
              dtype='datetime64[us]', freq='YS-JAN')
DatetimeIndex(['2025-12-31', '2026-12-31', '2027-12-31', '2028-12-31',
               '2029-12-31', '2030-12-31', '2031-12-31', '2032-12-31',
               '2033-12-31', '2034-12-31'],
              dtype='datetime64[us]', freq='YE-DEC')

In [81]:
df = pd.read_csv("data/weather.csv", parse_dates=["date"])

# re-sampling
df.set_index("date", inplace=True)

print(df[["temp_max", "temp_min"]].resample("YE").mean())

             temp_max  temp_min
date
2012-12-31  15.276776  7.289617
2013-12-31  16.058904  8.153973
2014-12-31  16.995890  8.662466
2015-12-31  17.427945  8.835616

In [82]:
df = pd.read_csv("data/employees.csv")
print(df["department_id"].isna().sum())
df.dropna(subset=["department_id"], inplace=True)
df["department_id"] = df["department_id"].astype("int64")
print(df)

1
     employee_id first_name last_name     email  phone_number      job_id  \
0            100     Steven      King     SKING  515.123.4567     AD_PRES
1            101      N_ann   Kochhar  NKOCHHAR  515.123.4568       AD_VP
2            102        Lex   De Haan   LDEHAAN  515.123.4569       AD_VP
3            103  Alexander    Hunold   AHUNOLD  590.423.4567     IT_PROG
4            104      Bruce     Ernst    BERNST  590.423.4568     IT_PROG
..           ...        ...       ...       ...           ...         ...
102          202        Pat       Fay      PFAY  603.123.6666      MK_REP
103          203      Susan    Mavris   SMAVRIS  515.123.7777      HR_REP
104          204    Hermann      Baer     HBAER  515.123.8888      PR_REP
105          205    Shelley   Higgins  SHIGGINS  515.123.8080      AC_MGR
106          206    William     Gietz    WGIETZ  515.123.8181  AC_ACCOUNT

      salary  commission_pct  manager_id  department_id
0    24000.0             NaN         NaN             90
1    17000.0             NaN       100.0             90
2    17000.0             NaN       100.0             90
3     9000.0             NaN       102.0             60
4     6000.0             NaN       103.0             60
..       ...             ...         ...            ...
102   6000.0             NaN       201.0             20
103   6500.0             NaN       101.0             40
104  10000.0             NaN       101.0             70
105  12000.0             NaN       101.0            110
106   8300.0             NaN       205.0            110

[106 rows x 10 columns]

In [83]:
# grouping aggregation
# calculate average salary of different department
print(df.groupby("department_id").groups)
print(df.groupby("department_id").get_group(20))
df2 = df.groupby("department_id")[["salary"]].mean()
df2["salary"] = df2["salary"].round(2)
print(df2)
df2 = df2.reset_index()
df2.sort_values("salary", ascending=False)

{10: [100], 20: [101, 102], 30: [14, 15, 16, 17, 18, 19], 40: [103], 50: [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99], 60: [3, 4, 5, 6, 7], 70: [104], 80: [45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 79], 90: [0, 1, 2], 100: [8, 9, 10, 11, 12, 13], 110: [105, 106]}
     employee_id first_name  last_name     email  phone_number  job_id  \
101          201    Michael  Hartstein  MHARTSTE  515.123.5555  MK_MAN
102          202        Pat        Fay      PFAY  603.123.6666  MK_REP

      salary  commission_pct  manager_id  department_id
101  13000.0             NaN       100.0             20
102   6000.0             NaN       201.0             20
                 salary
department_id
10              4400.00
20              9500.00
30              4150.00
40              6500.00
50              3475.56
60              5760.00
70             10000.00
80              8955.88
90             19333.33
100             8600.00
110            10150.00

    department_id    salary
8              90  19333.33
10            110  10150.00
6              70  10000.00
1              20   9500.00
7              80   8955.88
9             100   8600.00
3              40   6500.00
5              60   5760.00
0              10   4400.00
2              30   4150.00
4              50   3475.56

In [90]:
# average salary of different departments and different jobs
df2 = df.groupby(["department_id", "job_id"])[["salary"]].mean()
df2 = df2.reset_index()
df2["salary"] = df2["salary"].round(2)
df2 = df2.sort_values("salary", ascending=False)
print(df2)

    department_id      job_id    salary
13             90     AD_PRES  24000.00
14             90       AD_VP  17000.00
1              20      MK_MAN  13000.00
11             80      SA_MAN  12200.00
16            100      FI_MGR  12000.00
18            110      AC_MGR  12000.00
4              30      PU_MAN  11000.00
10             70      PR_REP  10000.00
12             80      SA_REP   8396.55
17            110  AC_ACCOUNT   8300.00
15            100  FI_ACCOUNT   7920.00
8              50      ST_MAN   7280.00
5              40      HR_REP   6500.00
2              20      MK_REP   6000.00
9              60     IT_PROG   5760.00
0              10     AD_ASST   4400.00
6              50    SH_CLERK   3215.00
7              50    ST_CLERK   2785.00
3              30    PU_CLERK   2780.00